### PR TITLE
Start the rewrite

### PR DESCRIPTION
**Pull request by RandomAltThingy**

### CODE REVIEW

**Comment by RandomAltThingy** [comment]
Idk why I put @TheDiamondYT that's my twitter xD

**Comment by CamoSplatty14** [comment]
@RandomAltThingy Oh, I thought that was your pocketmine name :P

**Comment by CamoSplatty14** [comment]
Oh, also, what did you mean by base? And what commands are you putting for the whole dynamic-ness (so I know which half of the commands I'll do)?

**Comment by RandomAltThingy** [comment]
I'm gonna do like 2 commands then you can follow the style I do in the first ones.

**Pull request merged**
